config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show]
    resources :categories,          only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.includes(products: [master: [:default_price, :images]]).find(params[:id])
    @categories = Spree::Taxonomy.all.eager_load(root: [children: :children])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
    @taxons = @product.taxons.includes(products: [master: [:default_price, :images]])
    @related_products = @taxons.flat_map(&:products).uniq.reject { |product| product == @product }
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><%= content_for?(:title) ? yield(:title) : "BIGBAG Store" %></title>
<%= csrf_meta_tags %>

<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

<!-- CUSTOM CSS -->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_header.html.erb
<div class="main-wrapper">

  <!-- HEADER -->
  <div class="header clearfix">

    <!-- TOPBAR -->
    <div class="topBar">
      <div class="container">
        <div class="row">
          <div class="col-md-6 hidden-sm hidden-xs">
            <ul class="list-inline">
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            </ul>
          </div>
          <div class="col-md-6 col-xs-12">
            <ul class="list-inline pull-right">
              <li><span><a data-toggle="modal" href='#login'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span></li>
              <li class="dropdown searchBox">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <form id="form01" action="product-grid-left-sidebar.html" method="post">
                  <li>
                    <span class="input-group">
                      <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                      <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                    </span>
                  </li>
                  </form>
                </ul>
              </li>
              <li class="dropdown">
                <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- NAVBAR -->
    <nav class="navbar navbar-main navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("img/logo.png", :alt => ""), potepan_index_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", potepan_index_path %></li>
            <li class="dropdown megaDropMenu active">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
              <ul class="dropdown-menu row">
                <li class="col-sm-3 col-xs-12">
                  <ul class="list-unstyled">
                    <li>Products Grid View</li>
                    <li class="active"><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                    <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                    <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                    <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                    <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                  </ul>
                </li>
                <li class="col-sm-3 col-xs-12">
                  <ul class="list-unstyled">
                    <li>Products List View</li>
                    <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                    <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                    <li class="listHeading">Others</li>
                    <li><a href="single_product.html">Single Product</a></li>
                    <li><a href="cart_page.html">Cart Page</a></li>
                  </ul>
                </li>
                <li class="col-sm-3 col-xs-12">
                  <ul class="list-unstyled">
                    <li>Checkout</li>
                    <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                    <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                    <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                    <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                    <li><a href="checkout_complete.html">Order Complete</a></li>
                  </ul>
                </li>
                <li class="col-sm-3 col-xs-12">
                  <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
                </li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
  </div>
</div>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sign_up_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/sign_up_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_bottom_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_first_category.html.erb
<li><a href="javascript:void(0);" data-toggle="collapse" data-target="#<%= first_category.name %>"><%= first_category.name %><i class="fa fa-plus"></i></a>
  <ul id="<%= first_category.name %>" class="collapse collapseItem">
    <% first_category.root.children.each do |second_category| %>
      <% if second_category.leaf? %>
        <li><a href="<%= second_category.id %>"><i class="fa fa-caret-right" aria-hidden="true"></i><%= second_category.name %><span>(<%= second_category.products.count %>)</span></a></li>
      <% else %>
        <li><a href="javascript:void(0);" data-toggle="collapse" data-target="#<%= second_category.name %>"><%= second_category.name %><i class="fa fa-plus"></i></a>
          <ul id="<%= second_category.name %>" class="collapse collapseItem">
            <% second_category.children.each do |third_category| %>
              <li><a href="<%= third_category.id %>"><i class="fa fa-caret-right" aria-hidden="true"></i><%= third_category.name %><span>(<%= third_category.products.count %>)</span></a></li>
            <% end %>
          </ul>
        </li>
      <% end %>
    <% end %>
  </ul>
</li>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(product.id) do %>
      <div class="productImage clearfix">
        <%= image_tag("#{product.display_image.attachment.url(:product)}", :alt => "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_top_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/show.html.erb
<% content_for :title do %>
  <%= @taxon.name %> - BIGBAG Store
<% end %>

<div class="main-wrapper">
  <%= render 'potepan/categories/top_light_section', taxon: @taxon %>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
          <div class="panel panel-default">
            <div class="panel-heading">商品カテゴリー</div>
            <div class="test-panel-body">
              <div class="panel-body">
                <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
                  <ul class="nav navbar-nav side-nav">
                    <%= render partial: "first_category", collection: @categories %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="panel panel-default filterNormal">
            <div class="panel-heading">色から探す</div>
            <div class="panel-body">
              <ul class="list-unstyled">
                <li><a href="#">ブラック<span>(15)</span></a></li>
                <li><a href="#">ホワイト<span>(10)</span></a></li>
                <li><a href="#">レッド<span>(7)</span></a></li>
                <li><a href="#">ブルー<span>(12)</span></a></li>
                <li><a href="#">オレンジ<span>(12)</span></a></li>
              </ul>
            </div>
          </div>
          <div class="panel panel-default filterNormal">
            <div class="panel-heading">サイズから探す</div>
            <div class="panel-body">
              <ul class="list-unstyled clearfix">
                <li><a href="#">S<span>(15)</span></a></li>
                <li><a href="#">M<span>(10)</span></a></li>
                <li><a href="#">L<span>(7)</span></a></li>
                <li><a href="#">XL<span>(12)</span></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div class="row filterArea">
            <div class="col-xs-6">
              <select name="guiest_id1" id="guiest_id1" class="select-drop">
                <option value="0">並び替え</option>
                <option value="1">人気順</option>
                <option value="2">安い順</option>
                <option value="3">新着順</option>
                <option value="3">高い順</option>
              </select>
            </div>
            <div class="col-xs-6">
              <div class="btn-group pull-right" role="group">
                <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
                <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="test-productBox">
              <%= render partial: "product", collection: @taxon.products %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render 'potepan/categories/bottom_light_section' %>
</div>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.first(RELATED_PRODUCTS_NUMBER_LIMIT).each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(related_product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment.url(:product), :alt => "products-img") %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= related_product.name %></h5>
            <h3><%= related_product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/show.html.erb
<% content_for :title do %>
<%= @product.name %> - BIGBAG Store
<% end %>

<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @product.name %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to "Home", potepan_index_path %>
            </li>
            <li class="active"><%= @product.name %></li>
        </div>
      </div>
    </div>
  </section>

  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, slide_index| %>
                    <div class="item <%= "active" if slide_index.zero? %>" data-thumb="<%= slide_index %>">
                      <%= image_tag("#{image.attachment.url(:large)}") %>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <% @product.images.each_with_index do |image, slide_index| %>
                      <div data-target="#carousel" data-slide-to="<%= slide_index %>" class="thumb">
                        <%= image_tag("#{image.attachment.url(:small)}") %>
                      </div>
                    <% end %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <ul class="list-inline">
                <li><%= link_to '一覧ページへ', potepan_category_path(@taxons.first.id), class: "fa fa-reply", "aria-hidden" => true %></li>
              </ul>
              <h2><%= @product.name %></h2>
              <h3><%= @product.display_price %></h3>
              <p><%= @product.description %></p>
              <span class="quick-drop">
                <select name="guiest_id3" id="guiest_id3" class="select-drop">
                  <option value="0">S</option>
                  <option value="1">M</option>
                  <option value="2">L</option>
                  <option value="3">XL</option>
                </select>
              </span>
              <span class="quick-drop resizeWidth">
                <select name="guiest_id4" id="guiest_id4" class="select-drop">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                </select>
              </span>
              <div class="btn-area">
                <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= render "related_products", related_products: @related_products %>
    </div>
  </section>
</div>